#!/bin/sh
set -e

if [ "$1" = remove ] && command -v systemctl >/dev/null 2>&1; then
    systemctl stop rkvm-server.service >/dev/null 2>&1 || true
    systemctl disable rkvm-server.service >/dev/null 2>&1 || true
fi

exit 0
